@echo off
echo Building NutriScan APK...
cd /d d:\nutriscanplus\nutriscan
echo Cleaning project...
flutter clean
echo Getting dependencies...
flutter pub get
echo Building APK...
flutter build apk --release --target-platform android-arm64
echo Build completed!
pause